(() => {
  'use strict';

  const uiExact = new Map([
    ['Knowledge map', '知识地图'],
    ['Learning route', '学习路线'],
    ['Core papers', '核心论文'],
    ['24 Core papers', '24 核心论文'],
    ['A paper-based learning route', '基于论文证据的学习路线'],
    ['How does a sliding ferroelectric actually switch?', '滑移铁电体究竟如何翻转？'],
    ['Supporting / branch papers', '补充 / 分支论文'],
    ['Editorial rule:', '编辑规则：'],
    ['Map', '知识地图'],
    ['MODULE', '模块'],
    ['Core paper', '核心论文'],
    ['Core papers', '核心论文'],
    ['Supporting', '补充文献'],
    ['Foundations', 'Foundations（基础）'],
    ['Multilayer', 'Multilayer（多层体系）'],
    ['Symmetry', 'Symmetry（对称性）'],
    ['Geometry', 'Geometry（几何）'],
    ['Relaxation', 'Relaxation（松弛）'],
    ['Scaling', 'Scaling（标度）'],
  ]);

  const termPairs = [
    ['Learning Sliding Ferroelectricity','滑移铁电学习站'],
    ['depinning universality class','退钉扎普适类'],
    ['finite-size scaling','有限尺寸标度'],
    ['system-size scaling','系统尺寸标度'],
    ['correlation length','关联长度'],
    ['critical depinning','临界退钉扎'],
    ['depinning criticality','退钉扎临界性'],
    ['depinning universality','退钉扎普适性'],
    ['depinning threshold','退钉扎阈值'],
    ['depinning field','退钉扎场'],
    ['zero-temperature depinning','零温退钉扎'],
    ['thermodynamic critical threshold','热力学临界阈值'],
    ['critical configuration','临界构型'],
    ['critical manifold','临界流形'],
    ['critical geometry','临界几何'],
    ['critical scaling','临界标度'],
    ['critical exponents','临界指数'],
    ['critical exponent','临界指数'],
    ['critical field','临界场'],
    ['critical force','临界力'],
    ['critical point','临界点'],
    ['criticality','临界性'],
    ['universality class','普适类'],
    ['universality test','普适性检验'],
    ['universality','普适性'],
    ['scaling collapse','标度坍缩'],
    ['scaling relations','标度关系'],
    ['scaling relation','标度关系'],
    ['corrections to scaling','标度修正'],
    ['power-law scaling','幂律标度'],
    ['power-law fit','幂律拟合'],
    ['power-law roughness','幂律粗糙度'],
    ['power-law','幂律'],
    ['log–log','双对数'],
    ['log-log','双对数'],
    ['asymptotic critical scaling','渐近临界标度'],
    ['velocity scaling','速度标度'],
    ['velocity exponent','速度指数'],
    ['roughness exponent','粗糙指数'],
    ['wandering exponent','游走指数'],
    ['structure factor','结构因子'],
    ['roughness correlation function','粗糙度关联函数'],
    ['global roughness','全局粗糙度'],
    ['local roughness','局域粗糙度'],
    ['roughness','粗糙度'],
    ['random-bond disorder','随机键无序'],
    ['random-field disorder','随机场无序'],
    ['quenched disorder','淬火无序'],
    ['quenched-disorder','淬火无序'],
    ['disorder strength','无序强度'],
    ['disorder landscape','无序景观'],
    ['defect landscape','缺陷景观'],
    ['pinning landscape','钉扎景观'],
    ['random pinning potential','随机钉扎势'],
    ['pinning potential','钉扎势'],
    ['pinning centre','钉扎中心'],
    ['pinning centres','钉扎中心'],
    ['pinning/depinning event','钉扎/退钉扎事件'],
    ['pinning-depinning','钉扎-退钉扎'],
    ['pinning/depinning','钉扎/退钉扎'],
    ['local pinning','局域钉扎'],
    ['pinning','钉扎'],
    ['de-pinning','退钉扎'],
    ['depinning','退钉扎'],
    ['creep law','蠕变定律'],
    ['creep motion','蠕变运动'],
    ['creep','蠕变'],
    ['random-field','随机场'],
    ['random field','随机场'],
    ['random-bond','随机键'],
    ['random bond','随机键'],
    ['RFIM','随机场伊辛模型'],
    ['QEW','淬火 Edwards–Wilkinson 模型'],
    ['elastic-manifold','弹性流形'],
    ['elastic manifold','弹性流形'],
    ['disordered elastic interface','无序弹性界面'],
    ['elastic interface','弹性界面'],
    ['elastic-line','弹性线'],
    ['elastic line','弹性线'],
    ['elastic kernel','弹性核'],
    ['effective elasticity','有效弹性'],
    ['elasticity','弹性性质'],
    ['long-range dipolar elasticity','长程偶极弹性'],
    ['order parameter','序参量'],
    ['bulk order-parameter model','体相序参量模型'],
    ['Ising order parameter','伊辛序参量'],
    ['Landau free energy','朗道自由能'],
    ['Landau potential','朗道势'],
    ['free-energy functional','自由能泛函'],
    ['free-energy terms','自由能项'],
    ['gradient energy','梯度能'],
    ['gradient term','梯度项'],
    ['phase-field','相场'],
    ['phase field','相场'],
    ['TDGL','含时金兹堡–朗道方程'],
    ['Ginzburg–Landau','金兹堡–朗道'],
    ['coarse-graining','粗粒化'],
    ['coarse graining','粗粒化'],
    ['coarse-grained','粗粒化'],
    ['coarse-grain','粗粒化'],
    ['diffuse interface','弥散界面'],
    ['diffuse wall','弥散畴壁'],
    ['diffuse-wall','弥散畴壁'],
    ['emergent elastic interface','涌现弹性界面'],
    ['emergent interface','涌现界面'],
    ['driven interface','受驱界面'],
    ['external drive','外部驱动'],
    ['lattice spacing','晶格间距'],
    ['grid points','网格点'],
    ['grid','网格'],
    ['white disorder','白噪声无序'],
    ['correlated noise','相关噪声'],
    ['noise strength','噪声强度'],
    ['seed statistics','随机种子统计'],
    ['seed convergence','随机种子收敛性'],
    ['dx convergence','dx 收敛性'],
    ['dt convergence','dt 收敛性'],
    ['size convergence','尺寸收敛性'],
    ['convergence','收敛性'],
    ['bulk observables','体相可观测量'],
    ['observables','可观测量'],
    ['observable','可观测量'],
    ['domain-wall motion','畴壁运动'],
    ['domain wall motion','畴壁运动'],
    ['pre-existing domain-wall motion','预存畴壁运动'],
    ['pre-existing domain wall','预存畴壁'],
    ['pre-existing wall','预存畴壁'],
    ['pre-existing DW','预存畴壁'],
    ['domain-wall speed','畴壁速度'],
    ['wall velocity','畴壁速度'],
    ['wall trajectory','畴壁轨迹'],
    ['wall geometry','畴壁几何'],
    ['wall motion','畴壁运动'],
    ['domain-wall','畴壁'],
    ['domain wall','畴壁'],
    ['DWs','畴壁'],
    ['DW','畴壁'],
    ['single-domain','单畴'],
    ['single domain','单畴'],
    ['domain structure','畴结构'],
    ['domain network','畴网络'],
    ['stacking domain','堆垛畴'],
    ['polar-domain','极性畴'],
    ['domain','畴'],
    ['nucleation-free switching','无成核翻转'],
    ['nucleation-free','无成核'],
    ['nucleation','成核'],
    ['overhang/bubble','悬垂/气泡状畴'],
    ['persistent overhangs','持续悬垂'],
    ['overhangs','悬垂'],
    ['overhang','悬垂'],
    ['bubbles','气泡状畴'],
    ['bubble','气泡状畴'],
    ['percolation-like invasion','类渗流侵入'],
    ['percolation-like behavior','类渗流行为'],
    ['percolative growth','渗流式生长'],
    ['avalanche-size exponent','雪崩尺寸指数'],
    ['avalanchelike','类雪崩'],
    ['avalanches','雪崩'],
    ['avalanche','雪崩'],
    ['hysteresis','滞回'],
    ['coercive field','矫顽场'],
    ['apparent critical field','表观临界场'],
    ['apparent switching field','表观翻转场'],
    ['local threshold','局域阈值'],
    ['threshold','阈值'],
    ['steady velocity','稳态速度'],
    ['fast flow','快速流动态'],
    ['flow','流动态'],
    ['transient','瞬态'],
    ['thermal activation','热激活'],
    ['thermally activated','热激活'],
    ['mobility','迁移率'],
    ['clean mobility','无无序迁移率'],
    ['clean-wall mobility','无无序畴壁迁移率'],
    ['superlubric dynamics','超润滑动力学'],
    ['superlubric','超润滑'],
    ['sliding ferroelectricity','滑移铁电'],
    ['sliding ferroelectrics','滑移铁电体'],
    ['sliding ferroelectric','滑移铁电体'],
    ['sliding-FE','滑移铁电'],
    ['sliding FE','滑移铁电'],
    ['sliding-induced','滑移诱导'],
    ['coherent sliding','整体协同滑移'],
    ['homogeneous coherent sliding','均匀协同滑移'],
    ['lateral sliding','横向滑移'],
    ['interlayer sliding','层间滑移'],
    ['sliding','滑移'],
    ['stacking registry','堆垛构型'],
    ['stacking configurations','堆垛构型'],
    ['stacking configuration','堆垛构型'],
    ['stacking sequence','堆垛序列'],
    ['stacking environment','堆垛环境'],
    ['stacking state','堆垛态'],
    ['stacking labels','堆垛标签'],
    ['stacking order','堆垛次序'],
    ['stacking operation','堆垛操作'],
    ['stacking-dependent','堆垛依赖'],
    ['stacking-resolved','堆垛分辨'],
    ['stacking','堆垛'],
    ['registry','堆垛构型'],
    ['relative interlayer translation','层间相对平移'],
    ['interlayer translation','层间平移'],
    ['lateral translation','横向平移'],
    ['translation','平移'],
    ['inversion symmetry','反演对称性'],
    ['crystal symmetry','晶体对称性'],
    ['symmetry breaking','对称性破缺'],
    ['symmetry-broken region','对称性破缺区域'],
    ['extrinsic symmetry breaking','外源对称性破缺'],
    ['symmetry','对称性'],
    ['interlayer charge transfer','层间电荷转移'],
    ['charge transfer','电荷转移'],
    ['out-of-plane polarization','面外极化'],
    ['interfacial polarization','界面极化'],
    ['polarization vector','极化矢量'],
    ['polarization reversal','极化反转'],
    ['switchable polarization','可翻转极化'],
    ['net polarization','净极化'],
    ['polarization','极化'],
    ['out-of-plane dipole','面外偶极'],
    ['interfacial dipoles','界面偶极'],
    ['switching pathway','极化翻转路径'],
    ['switching pathways','极化翻转路径'],
    ['switching event','翻转事件'],
    ['switching field','翻转场'],
    ['switching tendency','翻转倾向'],
    ['partial switching','部分翻转'],
    ['stepwise switching','分步翻转'],
    ['switching','极化翻转'],
    ['intermediate state','中间态'],
    ['metastable stacking','亚稳堆垛'],
    ['metastability','亚稳性'],
    ['layer-selective switching','层选择性翻转'],
    ['multi-interface','多界面'],
    ['multidomain kinetics','多畴动力学'],
    ['cycle-to-cycle variability','循环间波动'],
    ['cycle-to-cycle','循环间'],
    ['dwell time','驻留时间'],
    ['waiting time','等待时间'],
    ['Born effective charge','Born 有效电荷'],
    ['off-diagonal BEC','非对角 Born 有效电荷'],
    ['off-diagonal','非对角'],
    ['BEC','Born 有效电荷'],
    ['KPFM','开尔文探针力显微镜'],
    ['PFM','压电响应力显微镜'],
    ['HAADF-STEM','高角环形暗场扫描透射电子显微镜'],
    ['HRTEM','高分辨透射电子显微镜'],
    ['TEM','透射电子显微镜'],
    ['Raman imaging','拉曼成像'],
    ['Raman map','拉曼图'],
    ['Raman maps','拉曼图'],
    ['Raman','拉曼'],
    ['DFT','密度泛函理论'],
    ['AIMD','从头算分子动力学'],
    ['FRG','泛函重整化群'],
    ['RG','重整化群'],
    ['MD','分子动力学'],
    ['mean-field','平均场'],
    ['fixed point','不动点'],
    ['bilayer','双层'],
    ['trilayer','三层体系'],
    ['multilayer','多层体系'],
    ['monolayer','单层'],
    ['local barrier','局域势垒'],
    ['energy barrier','能垒'],
    ['barrier','势垒'],
    ['energy landscape','能量景观'],
    ['local landscape','局域景观'],
    ['landscape','能量景观'],
    ['long-range','长程'],
    ['nonlocality','非局域性'],
    ['Fourier','傅里叶'],
  ];

  termPairs.sort((a,b) => b[0].length - a[0].length);
  const termMap = new Map(termPairs.map(([term,zh]) => [term.toLowerCase(), zh]));
  const escaped = termPairs.map(([term]) => term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const termRe = new RegExp(`(^|[^A-Za-z0-9])(${escaped.join('|')})(?![A-Za-z0-9]|（)`, 'gi');

  function bilingualize(text) {
    if (!text || !/[A-Za-z]/.test(text)) return text;
    const trimmed = text.trim();
    if (uiExact.has(trimmed)) {
      const left = text.slice(0, text.indexOf(trimmed));
      const right = text.slice(text.indexOf(trimmed) + trimmed.length);
      return left + uiExact.get(trimmed) + right;
    }
    return text.replace(termRe, (match, prefix, term) => {
      const zh = termMap.get(term.toLowerCase());
      return zh ? `${prefix}${term}（${zh}）` : match;
    });
  }

  function shouldSkip(node) {
    const el = node.parentElement;
    if (!el) return true;
    if (el.closest('script,style,pre,code,.source-text')) return true;
    if (el.matches('.paper h3,.authors') || el.closest('.paper h3,.authors')) return true;
    return false;
  }

  function processTeachingText(root=document.body) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    for (const node of nodes) {
      if (shouldSkip(node)) continue;
      const next = bilingualize(node.nodeValue);
      if (next !== node.nodeValue) node.nodeValue = next;
    }
  }

  function improveReadingFlow() {
    const page = location.pathname.split('/').pop();
    const directNext = {
      'foundations.html':'switching-pathways.html',
      'depinning.html':'disorder-rfim.html',
      'disorder-rfim.html':'numerical-modeling.html',
      'numerical-modeling.html':'current-frontiers.html',
    };
    const next = document.querySelector('.next a:last-child');
    if (next && directNext[page]) next.setAttribute('href', directNext[page]);

    const style = document.createElement('style');
    style.textContent = `
      html,body{max-width:100%;overflow-x:hidden}
      .map-node h3,.module-side h2,.concept,.paper h3,.next a{overflow-wrap:anywhere;word-break:normal}
    `;
    document.head.appendChild(style);
  }

  processTeachingText();
  document.title = bilingualize(document.title);
  improveReadingFlow();
})();
